//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        public int ID { get; set; }
        [DisplayName("Product Name")]
        [Required(ErrorMessage ="Enter Product Name..")]
        public string Product_Name { get; set; }
        [DisplayName("Product Quantity")]
        [Required(ErrorMessage = "Enter Product Quantity..")]
        public string Product_Qnty { get; set; }
    }
}
