//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class purchase
    {
        public int ID { get; set; }
        [DisplayName("Purchase Product")]
        [Required(ErrorMessage = "Enter Purchase Product..")]
        public string Purchase_Prod { get; set; }
        [DisplayName("Purchase Quantity")]
        [Required(ErrorMessage = "Enter Purchase Quantity..")]
        public string Purchase_Qnty { get; set; }
        [DisplayName("Purchase Date")]
        [Required(ErrorMessage = "Enter Purchase Date..")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Purchase_Date { get; set; }
    }
}
